version: "3.8"

services:
  everyday-mysql:
    container_name: everyday-mysql
    image: mysql:8.3.0
    restart: always
    environment:
      - MYSQL_TCP_PORT=3307
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=SpringDemoDatabase
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: demo-app
    depends_on:
      - everyday-mysql
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      DB_HOST: localhost
      DB_PORT: 3307
      DB_NAME: SpringDemoDatabase
      SPRING_PROFILES_ACTIVE: local
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: